# Prometheus Configuration for O-RAN × Nephio RAG System
# Based on 2024 monitoring best practices

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'oran-nephio-rag'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules files
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # RAG Application metrics
  - job_name: 'oran-rag-app'
    static_configs:
      - targets: ['oran-rag-app:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # System metrics via Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker metrics via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Vector Database metrics (if Chroma exposes metrics)
  - job_name: 'chroma-db'
    static_configs:
      - targets: ['chroma-db:8001']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Custom health check endpoint
  - job_name: 'rag-health-check'
    static_configs:
      - targets: ['oran-rag-app:8080']
    scrape_interval: 30s
    metrics_path: /health/metrics
    scrape_timeout: 10s

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 15s
    metrics_path: /metrics

# Remote write configuration for long-term storage
remote_write:
  - url: "http://thanos-receive:19291/api/v1/receive"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Additional configurations
query:
  max_concurrency: 20
  timeout: 2m
  max_samples: 50000000