# O-RAN × Nephio RAG 系統 Prometheus 生產環境監控配置
# 高可用性、高性能的生產環境監控

global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s
  external_labels:
    cluster: 'oran-rag-prod'
    environment: 'production'
    region: 'us-east-1'

# 告警規則文件
rule_files:
  - "/etc/prometheus/rules/*.yml"

# 服務發現和監控目標
scrape_configs:
  # Prometheus 自監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s
    metrics_path: /metrics
    honor_labels: true

  # O-RAN RAG 主應用集群
  - job_name: 'oran-rag-app'
    static_configs:
      - targets: 
          - 'oran-rag-app-1:9100'
          - 'oran-rag-app-2:9100'
          - 'oran-rag-app-3:9100'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'oran-rag-app:9100'

  # Redis 主從集群監控
  - job_name: 'redis-master'
    static_configs:
      - targets: ['redis-master:6379']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: redis_role
        replacement: 'master'

  - job_name: 'redis-slave'
    static_configs:
      - targets: 
          - 'redis-slave-1:6379'
          - 'redis-slave-2:6379'
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: redis_role
        replacement: 'slave'

  # Redis Sentinel 監控
  - job_name: 'redis-sentinel'
    static_configs:
      - targets:
          - 'redis-sentinel-1:26379'
          - 'redis-sentinel-2:26379'
          - 'redis-sentinel-3:26379'
    scrape_interval: 60s
    metrics_path: /metrics

  # Node Exporter (系統監控)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: node_type
        replacement: 'application'

  # Nginx 負載均衡器監控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 30s
    metrics_path: /nginx_status
    params:
      format: ['prometheus']

  # cAdvisor (容器監控)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    honor_labels: true

  # Logstash 監控
  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:9600']
    scrape_interval: 60s
    metrics_path: /_node/stats/jvm,pipeline,process,reloads
    params:
      format: ['prometheus']

  # 自訂業務指標
  - job_name: 'oran-rag-business-metrics'
    static_configs:
      - targets: ['oran-rag-app:9101']
    scrape_interval: 30s
    metrics_path: /business-metrics
    honor_labels: true

  # 外部健康檢查
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://your-domain.com/health
          - https://your-domain.com/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL 憑證監控
  - job_name: 'blackbox-ssl'
    metrics_path: /probe  
    params:
      module: [ssl_expiry]
    static_configs:
      - targets:
          - https://your-domain.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # DNS 解析監控
  - job_name: 'blackbox-dns'
    metrics_path: /probe
    params:
      module: [dns_soa]
    static_configs:
      - targets:
          - your-domain.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# 告警管理器配置 (高可用)
alerting:
  alertmanagers:
    - static_configs:
        - targets: 
            - 'alertmanager-1:9093'
            - 'alertmanager-2:9093'
            - 'alertmanager-3:9093'
      path_prefix: /
      scheme: http
      timeout: 10s

# 遠程存儲配置 (生產環境建議)
remote_write:
  - url: "${REMOTE_WRITE_URL}"
    basic_auth:
      username: "${REMOTE_WRITE_USERNAME}"
      password: "${REMOTE_WRITE_PASSWORD}"
    queue_config:
      max_samples_per_send: 10000
      batch_send_deadline: 5s
      min_shards: 1
      max_shards: 200
      capacity: 100000
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

# 遠程讀取配置 (用於查詢歷史數據)
remote_read:
  - url: "${REMOTE_READ_URL}"
    basic_auth:
      username: "${REMOTE_READ_USERNAME}"
      password: "${REMOTE_READ_PASSWORD}"
    read_recent: true

# 存儲配置
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    path: /prometheus
    wal-compression: true