# O-RAN × Nephio RAG 系統 Prometheus 監控配置
# 開發環境用的監控配置

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'oran-rag-dev'
    environment: 'development'

# 告警規則文件
rule_files:
  - "/etc/prometheus/rules/*.yml"

# 服務發現和監控目標
scrape_configs:
  # Prometheus 自監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # O-RAN RAG 主應用
  - job_name: 'oran-rag-app'
    static_configs:
      - targets: ['oran-rag-app:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Redis 監控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter (系統監控)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx 監控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 30s
    metrics_path: /nginx_status
    params:
      format: ['prometheus']

  # Docker 容器監控
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL 監控 (如果啟用)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s
    metrics_path: /metrics

  # Elasticsearch 監控 (如果啟用)
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 60s
    metrics_path: /_prometheus/metrics

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# 遠程寫入配置 (可選)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "user"
#       password: "pass"

# 遠程讀取配置 (可選)
# remote_read:
#   - url: "https://your-remote-storage/api/v1/read"
#     basic_auth:
#       username: "user"
#       password: "pass"